name: Build & Publish

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io

jobs:

  ti-cgt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "${{ env.REGISTRY }}/${{ github.repository_owner }}/ti-cgt-c2000:latest"
